
# The data_path contains folders, which in turn contain test and train files (csv).
# The run_script will run experiments for all of these folders  
dataset:
  data_path: datasets/adapter_scm
  out_path: False # if False, the results are saved in the data_path
  pattern: "Dies ist ein <mask> <mask> Waffenlieferungen an die Ukraine: "
  verbalizer:
    argumentagainst: "Argument gegen"
    argumentfor: "Argument für"
    claimagainst: "claim gegen"
    claimfor: "claim für"
    nostance: "Satz ohne"
  prefix: ukraine
    
adapter:
  arch: pfeiffer
  c_rate: 16 # can also be a list, then a subfolder for each value is created for each experiment
  learning_rate: 5e-5
  max_epochs: 30
  number_of_runs: 5
  per_device_train_batch_size: 2
  